node {
    def buildNumber = env.BUILD_NUMBER as int
        if (buildNumber > 1) milestone(buildNumber - 1)
        milestone(buildNumber)
    def app

    stage('Clone repository') {
        /* Cloning the Repository to our Workspace */

        checkout scm
    }

    stage('Build image') {
        /* This builds the actual image */
        // app = docker.build("d1")
        sh "docker build -t d1 -f ./dockerfiles/tests/Dockerfile ."
    }

       stage('run') {
        /* This builds the actual image */

      sh "docker run d1"
    }
}
